export interface TestDefinition {
  id: string
  name: string
  fullName: string
  instruction: string
  prefix: string
  scale: { labels: string[]; min: number; max: number }
  questions: string[]
  controlQuestion?: { index: number; expectedValue: number; message: string }
  estimatedMinutes: string
}

export const TESTS: Record<string, TestDefinition> = {
  kse53: {
    id: "kse53",
    name: "KSE-53",
    fullName: "Kısa Semptom Envanteri",
    instruction:
      "Son bir hafta içerisinde aşağıdaki durumların sizi ne ölçüde etkilediğini değerlendirerek yanındaki daireye uygun rakamı (0-4) yazınız.",
    prefix: "",
    scale: {
      labels: ["Hiç", "Biraz", "Orta Derecede", "Epey", "Çok Fazla"],
      min: 0,
      max: 4,
    },
    estimatedMinutes: "8–10 dk",
    controlQuestion: {
      index: 27, // 0-based (madde 28)
      expectedValue: 2, // "Orta Derecede"
      message: "Bu kontrol sorusudur. Lütfen \"Orta Derecede\" seçeneğini işaretleyiniz.",
    },
    questions: [
      "İçinizdeki sinirlilik ve titreme hali",
      "Baygınlık, baş dönmesi",
      "Bir başka kişinin düşüncelerinizi kontrol edeceği fikri",
      "Başınıza gelen sıkıntılardan dolayı başkalarının suçlu olduğu duygusu",
      "Olayları hatırlamada güçlük",
      "Çok kolayca kızıp öfkelenme",
      "Göğüs (kalp) bölgesinde ağrılar",
      "Meydanlık (açık) alanlardan korkma duygusu",
      "Yaşamınıza son verme düşünceleri",
      "İnsanların çoğuna güvenilmeyeceği hissi",
      "İştahta bozukluklar",
      "Hiçbir nedeni olmayan ani korkular",
      "Kontrol edemediğiniz duygu patlamaları",
      "Başka insanlarla beraberken bile yalnızlık hissetme",
      "İşleri bitirme konusunda kendini engellenmiş hissetme",
      "Yalnızlık hissetme",
      "Hüzünlü, kederli hissetme",
      "Hiçbir şeye ilgi duymama",
      "Ağlamaklı hissetme",
      "Kolayca incinebilme, kırılma",
      "İnsanların sizi sevmediğine, kötü davrandığına inanmak",
      "Kendini diğerlerinden daha aşağı görme",
      "Mide bozukluğu, bulantı",
      "Diğerlerinin sizi gözlediği ya da hakkınızda konuştuğu duygusu",
      "Uykuya dalmada güçlük",
      "Yaptığınız şeyleri tekrar tekrar doğru mu diye kontrol etme",
      "Karar vermede güçlükler",
      "Bu soruyu okuyorsanız \"Orta Derecede\" seçeneğini işaretleyiniz",
      "Otobüs, tren, metro gibi araçlarla seyahat etmekten korkma",
      "Nefes darlığı, nefessiz kalma",
      "Sıcak, soğuk basmaları",
      "Sizi korkuttuğu için bazı eşya, yer, etkinliklerden uzak kalma",
      "Kafanızın bomboş kalması",
      "Bedeninizin bazı bölgelerinde uyuşmalar, karıncalanmalar",
      "Günahlarınız için cezalandırılmanız gerektiği düşüncesi",
      "Gelecekle ilgili umutsuzluk duyguları içinde olmak",
      "Konsantrasyonda güçlük/zorlanma",
      "Bedenin bazı bölgelerinde zayıflık, güçsüzlük hissi",
      "Kendini gergin ve tedirgin hissetme",
      "Ölme ve ölüm üzerinde düşünceler",
      "Birini dövme, ona zarar verme, yaralama isteği",
      "Bir şeyleri kırma/dökme isteği",
      "Diğerlerinin yanında kendinin çok fazla farkında olmak",
      "Kalabalıklarda rahatsızlık duymak",
      "Bir başka insana hiç yakınlık duymamak",
      "Dehşet ve panik nöbetleri",
      "Sık sık tartışmaya girme",
      "Yalnız bırakıldığında sinirlilik hissetme",
      "Başarılarınız için yeterince takdir görmediğiniz düşüncesi",
      "Yerinde duramayacak kadar tedirgin hissetme",
      "Kendini değersiz görme, değersizlik duyguları",
      "İzin verdiğiniz takdirde insanların sizi sömüreceği duygusu",
      "Suçluluk duyguları",
      "Aklınızda bir bozukluk olduğu fikri",
    ],
  },
  bfi2: {
    id: "bfi2",
    name: "BFI-2",
    fullName: "Beş Faktör Kişilik Envanteri",
    instruction:
      "Aşağıda sizi kısmen tanımlayan (ya da pek tanımlayamayan) bir takım özellikler sunulmaktadır. Lütfen aşağıda verilen özelliklerin sizi ne oranda yansıttığını ya da yansıtmadığını belirtmek için sizi en iyi tanımlayan ifadeyi işaretleyiniz. Hiçbir maddeyi atlamayınız.",
    prefix: "Kendimi ........ biri olarak görüyorum.",
    scale: {
      labels: [
        "Hiç katılmıyorum",
        "Biraz katılmıyorum",
        "Kararsızım",
        "Biraz katılıyorum",
        "Tamamen katılıyorum",
      ],
      min: 1,
      max: 5,
    },
    estimatedMinutes: "10–15 dk",
    questions: [
      "Dışadönük, sosyal",
      "Şefkatli, yumuşak kalpli",
      "Dağınık olma eğiliminde",
      "Rahat, stresle baş edebilen",
      "Sanatsal ilgileri az olan",
      "Atılgan, girişken",
      "Saygılı, başkalarına saygılı davranan",
      "Tembelliğe eğilimli",
      "Bir aksilik yaşadığında iyimserliğini koruyan",
      "Farklı birçok şeye merak duyan",
      "Nadiren heyecanlanan ya da heveslenen",
      "Başkalarında hata arama eğiliminde olan",
      "Güvenilir, istikrarlı",
      "Dakikası dakikasına uymayan, ruh hali inişli çıkışlı",
      "Yaratıcı, bir işi yapmanın akıllıca yöntemlerini bulan",
      "Sessiz olmaya eğilimli",
      "Başkalarının halinden pek anlamayan",
      "Sistemli, her şeyin düzenli olmasını seven",
      "Gergin olabilen",
      "Sanat, müzik ya da edebiyatla çok ilgili",
      "Baskın, lider gibi davranan",
      "Başkaları ile tartışma başlatan",
      "İşe başlamakta zorlanan",
      "Güvenli, kendiyle barışık",
      "Entelektüel, felsefi tartışmalardan kaçınan",
      "Başkalarından daha az hareketli",
      "Affedici bir yapısı olan",
      "Biraz özensiz olabilen",
      "Duygusal olarak dengeli, keyfi kolay kaçmayan",
      "Yaratıcı yönü zayıf olan",
      "Bazen utangaç, içe dönük",
      "Yardımsever, bencil olmayan",
      "Etrafını temiz ve derli toplu tutan",
      "Çok endişelenen",
      "Sanata ve estetiğe değer veren",
      "Başkalarını etkilemede zorlanan",
      "Zaman zaman başkalarına kaba davranan",
      "Verimli, iş bitiren",
      "Sıkça üzgün hisseden",
      "Çok yönlü, derin düşünen",
      "Enerji dolu",
      "Başkalarının iyi niyetinden şüphe eden",
      "Sözünde duran, başkalarının güvenebileceği",
      "Duygularını kontrol altında tutan",
      "Zihinde canlandırma yapmada zorlanan",
      "Konuşkan",
      "Soğuk ve başkalarını umursamayan",
      "Arkasını toplamayan, dağınık bırakan",
      "Nadiren kaygılanan ya da korkan",
      "Şiir ve tiyatroyu sıkıcı bulan",
      "Kararları başkalarının vermesini tercih eden",
      "Kibar, başkalarına nezaketle yaklaşan",
      "Kolay vazgeçmeyen, işin sonunu getiren",
      "Depresif, hüzünlü hissetmeye eğilimli",
      "Soyut konulara az ilgi duyan",
      "Coşku dolu",
      "Başkaları hakkında hep iyi düşünen",
      "Bazen sorumsuzca davranan",
      "Değişken mizaçlı, çabuk sinirlenen",
      "Özgün, yeni fikirler üreten",
    ],
  },
}

export const MUDURLUKLER = [
  "Afet İşleri Müdürlüğü",
  "Akıllı Ulaşım Sistemleri Müdürlüğü",
  "Basın ve Yayın Müdürlüğü",
  "Destek Hizmetleri Müdürlüğü",
  "Emlak ve İstimlak Müdürlüğü",
  "Fen İşleri Müdürlüğü",
  "Gelirler Müdürlüğü",
  "Gençlik ve Spor Hizmetleri Müdürlüğü",
  "Halkla İlişkiler Müdürlüğü",
  "Hukuk İşleri Müdürlüğü",
  "İklim Değişikliği ve Sıfır Atık Müdürlüğü",
  "İmar ve Şehircilik Müdürlüğü",
  "İnovasyon ve Teknoloji Müdürlüğü",
  "İnsan Kaynakları ve Eğitim Müdürlüğü",
  "İşletme ve İştirakler Müdürlüğü",
  "Koordinasyon İşleri Müdürlüğü",
  "Kültür İşleri Müdürlüğü",
  "Mali Hizmetler Müdürlüğü",
  "Muhtarlık İşleri Müdürlüğü",
  "Özel Kalem Müdürlüğü",
  "Park ve Bahçeler Müdürlüğü",
  "Plan ve Proje Müdürlüğü",
  "Ruhsat ve Denetim Müdürlüğü",
  "Sosyal Destek Hizmetleri Müdürlüğü",
  "Strateji Geliştirme Müdürlüğü",
  "Temizlik İşleri Müdürlüğü",
  "Veteriner İşleri Müdürlüğü",
  "Yapı Kontrol Müdürlüğü",
  "Yazı İşleri Müdürlüğü",
  "Zabıta Müdürlüğü",
]
